#
# ci.yml
#
# Run tests for all pushed commits and opened pull requests on Github.
#

name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Bun + Astro build
        run: |
          bun i
          bun run build
        env:
          CI: true
